TUGAS 3 DATA MINING
NAMA : LAI, MARCELLINO AGUSTIAN
NIM : A11.2018.10854
KELOMPOK : A11.4617

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Jakarta' 165.0 80.0]
 ['Semarang' 162.0 55.0]
 ['Surabaya' nan 70.0]
 ['Semarang' 140.0 nan]
 ['Jakarta' 168.0 58.0]
 ['Surabaya' 180.0 85.0]
 ['Surabaya' nan 95.0]
 ['Jakarta' 160.0 75.0]
 ['Semarang' 168.0 88.0]
 ['Semarang' 185.0 nan]]


In [ ]:
print(y)

['Ya' 'Tidak' 'Tidak' 'Ya' 'Tidak' 'Tidak' 'Ya' 'Ya' 'Ya' 'Tidak']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[: , 1:3])

In [ ]:
print(x)

[['Jakarta' 165.0 80.0]
 ['Semarang' 162.0 55.0]
 ['Surabaya' 166.0 70.0]
 ['Semarang' 140.0 75.75]
 ['Jakarta' 168.0 58.0]
 ['Surabaya' 180.0 85.0]
 ['Surabaya' 166.0 95.0]
 ['Jakarta' 160.0 75.0]
 ['Semarang' 168.0 88.0]
 ['Semarang' 185.0 75.75]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 165.0 80.0]
 [0.0 1.0 0.0 162.0 55.0]
 [0.0 0.0 1.0 166.0 70.0]
 [0.0 1.0 0.0 140.0 75.75]
 [1.0 0.0 0.0 168.0 58.0]
 [0.0 0.0 1.0 180.0 85.0]
 [0.0 0.0 1.0 166.0 95.0]
 [1.0 0.0 0.0 160.0 75.0]
 [0.0 1.0 0.0 168.0 88.0]
 [0.0 1.0 0.0 185.0 75.75]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 0 1 0 0 1 1 1 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1 )

In [ ]:
print(x_train)

[[0.0 0.0 1.0 166.0 95.0]
 [1.0 0.0 0.0 168.0 58.0]
 [1.0 0.0 0.0 165.0 80.0]
 [0.0 1.0 0.0 140.0 75.75]
 [0.0 1.0 0.0 162.0 55.0]
 [1.0 0.0 0.0 160.0 75.0]
 [0.0 1.0 0.0 168.0 88.0]
 [0.0 0.0 1.0 180.0 85.0]]


In [ ]:
print(y_train)

[1 0 1 1 0 1 1 0]


In [ ]:
print(y_test)

[0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:,4:])
x_test[:, 4:] = sc.transform(x_test[:,4:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 166.0 1.4179990157090405]
 [1.0 0.0 0.0 168.0 -1.4132165569714048]
 [1.0 0.0 0.0 165.0 0.27020891867642766]
 [0.0 1.0 0.0 140.0 -0.054998275482812706]
 [0.0 1.0 0.0 162.0 -1.6427745763779273]
 [1.0 0.0 0.0 160.0 -0.11238778033444335]
 [0.0 1.0 0.0 168.0 0.8823636370938213]
 [0.0 0.0 1.0 180.0 0.6528056176872986]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 166.0 -0.49498447934531437]
 [0.0 1.0 0.0 185.0 -0.054998275482812706]]
